### ISSUE TITLE
concurrent use of SHA1 digest triggers ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jsvd** [jruby/jruby-openssl#178]
On JRuby:

```
% ruby -v
jruby 9.2.3.0 (2.5.0) 2018-11-09 5833e2d Java HotSpot(TM) 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 +jit [darwin-x86_64]
% ruby -e 'require "openssl"; cipher = OpenSSL::Digest::SHA1.new; a = Thread.new { 100_000.times { cipher.hexdigest("teste") } }; b = Thread.new { 100_000.times { cipher.hexdigest("teste") } }; a.join; b.join'
warning: thread "Ruby-0-Thread-1: -e:1" terminated with exception (report_on_exception is true):
java.lang.ArrayIndexOutOfBoundsException: 4
	at org.bouncycastle.crypto.digests.GeneralDigest.update(Unknown Source)
	at org.bouncycastle.crypto.digests.GeneralDigest.finish(Unknown Source)
	at org.bouncycastle.crypto.digests.SHA1Digest.doFinal(Unknown Source)
	at org.bouncycastle.jcajce.provider.digest.BCMessageDigest.engineDigest(Unknown Source)
	at java.security.MessageDigest.digest(MessageDigest.java:365)
	at org.jruby.ext.openssl.Digest.finish(Digest.java:204)
	at org.jruby.ext.openssl.Digest$INVOKER$i$0$0$finish.call(Digest$INVOKER$i$0$0$finish.gen)
	at org.jruby.RubyClass.finvoke(RubyClass.java:547)
	at org.jruby.runtime.Helpers.invoke(Helpers.java:363)
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:352)
	at org.jruby.ext.digest.RubyDigest$DigestInstance.digest(RubyDigest.java:321)
	at org.jruby.ext.digest.RubyDigest$DigestInstance.hexdigest(RubyDigest.java:340)
	at org.jruby.ext.digest.RubyDigest$DigestInstance$INVOKER$s$0$1$hexdigest.call(RubyDigest$DigestInstance$INVOKER$s$0$1$hexdigest.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:797)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at DashE.invokeOther1:hexdigest(-e:1)
	at DashE.RUBY$block$-e$1(-e:1)
```

on MRI:

```
% rvm 2.5.3 do ruby -e 'require "openssl"; cipher = OpenSSL::Digest::SHA1.new; a = Thread.new { 100_000.times { cipher.hexdigest("teste") } }; b = Thread.new { 100_000.times { cipher.hexdigest("teste") } }; a.join; b.join; puts cipher.hexdigest("teste")'
2e6f9b0d5885b6010f9167787445617f553a735f
```

It seems BC Digest instances can't be shared across threads?

**Comment by kares** [comment]
yes, it will work fine under MRI with a GIL ... if you put in a lock around digest's use it might work on JRuby.
not sure we would be fixing these, non on the Java security objects provide a thread-safety guarantee (it would make them slightly slower), in this particular case `java.security.MessageDigest` isn't thread-safe.

would say its to be fixed at the application level. 
why did you decide to report - do you feel like these should be thread-safe?
