### ISSUE TITLE
Tomcat 8/9 app deployment - NameError: cannot load (ext) (org.jruby.ext.openssl.OpenSSL)

### ISSUE THREAD

**Issue by fun-ruby** [jruby/jruby-openssl#196]
I'm getting this error deploying myapp.war in Tomcat 9/8. It's a standard deployment so didn't expect to get stalled on this.

### Env
* rails 5.2.3
* jruby 9.2.8.0
* jruby-openssl 0.10.2 (also tried 0.10.3 and 0.10.4)
* openjdk 1.8.0_242
* tomcat 9.0.16 (and 8.5.39) - clean install
* ubuntu 18.04

Also tried updating `/etc/ssl/certs/java/cacerts` and more recent versions of `jruby-openssl` without any luck.

I suspect the problem may be environment related, but not sure where to start looking.

Any ideas?

### Stack Trace
```
27-Mar-2020 12:31:03.719 INFO [main] org.apache.catalina.core.ApplicationContext.log INFO: jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff OpenJDK 64-Bit Server VM 25.242-b08 
on 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08 +jit [linux-x86_64]
27-Mar-2020 12:31:03.721 INFO [main] org.apache.catalina.core.ApplicationContext.log INFO: using a shared (threadsafe!) runtime
27-Mar-2020 12:31:15.103 INFO [main] org.apache.catalina.core.ApplicationContext.log An exception happened during JRuby-Rack startup
cannot load (ext) (org.jruby.ext.openssl.OpenSSL)
--- System
jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff OpenJDK 64-Bit Server VM 25.242-b08 on 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08 +jit [linux-x86_64]
Time: 2020-03-27 12:31:15 -0400
Server: Apache Tomcat/9.0.16 (Ubuntu)
jruby.home: uri:classloader://META-INF/jruby.home

--- Context Init Parameters:
jruby.max.runtimes = 1
jruby.min.runtimes = 1
public.root = /
rails.env = production

--- Backtrace
NameError: cannot load (ext) (org.jruby.ext.openssl.OpenSSL)
          load_ext at org/jruby/ext/jruby/JRubyUtilLibrary.java:201
            <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:31
           require at org/jruby/RubyKernel.java:987
            <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1
           require at org/jruby/RubyKernel.java:987
            <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1
           require at org/jruby/RubyKernel.java:987
            <main> at /var/lib/tomcat9/webapps/myapp/WEB-INF/gems/gems/activesupport-5.2.3/lib/active_support/key_generator.rb:1
           require at org/jruby/RubyKernel.java:987
            <main> at /var/lib/tomcat9/webapps/myapp/WEB-INF/gems/gems/activesupport-5.2.3/lib/active_support/key_generator.rb:4
           require at org/jruby/RubyKernel.java:987
            <main> at /var/lib/tomcat9/webapps/myapp/WEB-INF/gems/gems/railties-5.2.3/lib/rails/application.rb:1
...

27-Mar-2020 12:31:15.109 SEVERE [main] org.apache.catalina.core.ApplicationContext.log ERROR: initialization failed
 org.jruby.rack.RackInitializationException: cannot load (ext) (org.jruby.ext.openssl.OpenSSL)
        from org/jruby/ext/jruby/JRubyUtilLibrary.java:201:in `load_ext'
        from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:31:in `<main>'
        from org/jruby/RubyKernel.java:987:in `require'
        from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1:in `<main>'
...

Caused by: org.jruby.exceptions.NameError: (NameError) cannot load (ext) (org.jruby.ext.openssl.OpenSSL)
        at org.jruby.ext.jruby.JRubyUtilLibrary.load_ext(org/jruby/ext/jruby/JRubyUtilLibrary.java:201)
        at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:31)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:987)
        at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1)
...

Caused by: java.lang.NoSuchMethodError: org.jruby.gen.org$jruby$ext$openssl$OpenSSL$POPULATOR.populateMethod(Lorg/jruby/internal/runtime/methods/JavaMethod;ILjava/lang/String;ZLorg/jruby/internal/runtime/methods/CallConfiguration;ZLjava/lang/Class;Ljava/lang/String;Ljava/lang/Class;[Ljava/lang/Class;)V
        at org.jruby.gen.org$jruby$ext$openssl$OpenSSL$POPULATOR.populate(org$jruby$ext$openssl$OpenSSL$POPULATOR.java:25)
        at org.jruby.RubyModule.defineAnnotatedMethodsIndividually(RubyModule.java:1235)
...
```

**Comment by headius** [comment]
This seems to be a dependency conflict. The method mentioned by the NoSuchMethodError should definitely exist, and if this error is happening you have a mismatch between the jruby-openssl version and the JRuby version it's expected to use.

Is it possible that your Tomcat has another JRuby in it, or maybe there's some environment variable pointing at another version of JRuby?

**Comment by fun-ruby** [comment]
Thanks for chiming in @headius. Your point does give me a "light-bulb" moment - maybe `jruby-openssl` is actually missing.

I am upgrading my app from JRuby 1.7.19 and the warbler config has this setting enabled.

```
config/warble.rb
  ...
  config.move_jars_to_webinf_lib = true
```

The packaged .war file does have jars moved in to `WEB-INF/lib/`

```
...
WEB-INF/lib/gems-gems-jruby-openssl-0.10.3-java-lib-jopenssl.jar
WEB-INF/lib/gems-gems-jruby-openssl-0.10.3-java-lib-org-bouncycastle-bcpkix-jdk15on-1.62-bcpkix-jdk15on-1.62.jar
WEB-INF/lib/gems-gems-jruby-openssl-0.10.3-java-lib-org-bouncycastle-bcprov-jdk15on-1.62-bcprov-jdk15on-1.62.jar
WEB-INF/lib/gems-gems-jruby-openssl-0.10.3-java-lib-org-bouncycastle-bctls-jdk15on-1.62-bctls-jdk15on-1.62.jar
...
WEB-INF/lib/jruby-core-9.2.8.0-complete.jar
WEB-INF/lib/jruby-rack-1.1.21.jar
WEB-INF/lib/jruby-stdlib-9.2.8.0.jar
```

And I get the `NameError: cannot load ...` error on application startup.

Removing the `config.move_jars_to_webinf_lib` line and repackage allowed the application to startup correctly. The `WEB-INF/lib/` directory contains only the minimal jars.
```
WEB-INF/lib/jruby-core-9.2.8.0-complete.jar
WEB-INF/lib/jruby-rack-1.1.21.jar
WEB-INF/lib/jruby-stdlib-9.2.8.0.jar
```

Perhaps this is a bug in loading gem jars from `WEB-INF/lib/`?

**Comment by headius** [comment]
@fun-ruby If the jar were not accessible at all, we would not be seeing a `NoMethodError`. That error is only thrown by the JVM if you have compiled code attempting to call a method that should not have been there when it was compiled. Basically, something changed out from underneath the code, which is why I suspect there's a conflicting jar. 

If you are still able to help investigate, look for all jars named `jopenssl.jar`, possibly by manually unpacking the war file and the jruby-complete jar. I believe we'll find two of them.

**Comment by fun-ruby** [comment]
@headius I can only find references to `openssl` in `jruby-stdlib` jar. See unpacked content below. I've made effort to set `jopenssl` at version `0.10.2` so it matches the version included in `jruby-stdlib`, without luck.

```
unzip -l my.jar | grep '\.jar'
...
 15193198  2020-06-02 14:13   WEB-INF/gems/gems/jruby-jars-9.2.8.0/lib/jruby-core-9.2.8.0-complete.jar
 11224621  2020-06-02 14:13   WEB-INF/gems/gems/jruby-jars-9.2.8.0/lib/jruby-stdlib-9.2.8.0.jar
      283  2020-06-02 14:13   WEB-INF/gems/gems/jruby-openssl-0.10.2-java/lib/jopenssl.jar
      283  2020-06-02 14:13   WEB-INF/gems/gems/jruby-openssl-0.10.2-java/lib/org/bouncycastle/bcpkix-jdk15on/1.61/bcpkix-jdk15on-1.61.jar
      283  2020-06-02 14:13   WEB-INF/gems/gems/jruby-openssl-0.10.2-java/lib/org/bouncycastle/bcprov-jdk15on/1.61/bcprov-jdk15on-1.61.jar
      283  2020-06-02 14:13   WEB-INF/gems/gems/jruby-openssl-0.10.2-java/lib/org/bouncycastle/bctls-jdk15on/1.61/bctls-jdk15on-1.61.jar
...

  1153670  2020-06-02 14:13   WEB-INF/lib/gems-gems-jruby-openssl-0.10.2-java-lib-jopenssl.jar
   866346  2020-06-02 14:13   WEB-INF/lib/gems-gems-jruby-openssl-0.10.2-java-lib-org-bouncycastle-bcpkix-jdk15on-1.61-bcpkix-jdk15on-1.61.jar
  4543663  2020-06-02 14:13   WEB-INF/lib/gems-gems-jruby-openssl-0.10.2-java-lib-org-bouncycastle-bcprov-jdk15on-1.61-bcprov-jdk15on-1.61.jar
   562610  2020-06-02 14:13   WEB-INF/lib/gems-gems-jruby-openssl-0.10.2-java-lib-org-bouncycastle-bctls-jdk15on-1.61-bctls-jdk15on-1.61.jar
...

 15193198  2020-06-02 14:13   WEB-INF/lib/jruby-core-9.2.8.0-complete.jar
   268278  2020-06-02 14:13   WEB-INF/lib/jruby-rack-1.1.21.jar
 11224621  2020-06-02 14:13   WEB-INF/lib/jruby-stdlib-9.2.8.0.jar
```

```
unzip -l WEB-INF/lib/jruby-stdlib-9.2.8.0.jar | grep openssl
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl/
      461  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl.rb
       35  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl/digest.rb
       38  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl/buffering.rb
       35  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl/config.rb
       35  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl/cipher.rb
     3390  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl/x509.rb
       69  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl/.jrubydir
       32  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl/ssl.rb
      444  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/openssl/bn.rb
       24  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl21/.jrubydir

  1153670  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl.jar

     4204  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/gems/shared/specifications/default/jruby-openssl-0.10.2-java.gemspec
       23  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl.rb
     1114  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl/_compat23.rb
       37  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl/.jrubydir
     3378  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/x509-internal.rb
     6426  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/ssl-internal.rb
      525  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/cipher.rb
       98  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/x509.rb
      102  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/.jrubydir
       96  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/ssl.rb
      445  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/bn.rb
       24  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/.jrubydir
      525  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl/cipher.rb
     4012  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl/x509.rb
       69  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl/.jrubydir
    10606  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl/ssl.rb
      609  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl/bn.rb
       24  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/.jrubydir
      479  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl.rb
      588  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/digest.rb
     9361  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/buffering.rb
    12227  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl19/openssl/config.rb
      306  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/digest.rb
      306  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/buffering.rb
      169  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/x509-internal.rb
      168  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/ssl-internal.rb
      145  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/pkey.rb
      459  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/config.rb
      306  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/x509.rb
      129  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/.jrubydir
      306  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/ssl.rb
      306  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/bn.rb
      660  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/pkcs5.rb
      465  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl.rb
      855  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/digest.rb
     9918  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/buffering.rb
      669  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/pkey.rb
    12267  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/config.rb
      542  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/cipher.rb
     5972  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/x509.rb
       77  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/.jrubydir
    17005  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/ssl.rb
      684  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/bn.rb
       24  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/.jrubydir
     3206  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/pkcs12.rb
      306  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/openssl/cipher.rb
     1642  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb
      184  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl/version.rb
      461  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl.rb
      976  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl/digest.rb
     9632  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl/buffering.rb
     7417  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/jopenssl22/openssl/config.rb
```

```
unzip -l WEB-INF/lib/jruby-stdlib-9.2.8.0.jar | grep bouncy
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcprov-jdk15on/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcprov-jdk15on/1.61/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcpkix-jdk15on/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcpkix-jdk15on/1.61/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bctls-jdk15on/
        0  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bctls-jdk15on/1.61/
       29  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcprov-jdk15on/1.61/.jrubydir
  4543663  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcprov-jdk15on/1.61/bcprov-jdk15on-1.61.jar
       28  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bctls-jdk15on/1.61/.jrubydir
       10  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bctls-jdk15on/.jrubydir
       49  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/.jrubydir
       10  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcprov-jdk15on/.jrubydir
   866346  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcpkix-jdk15on/1.61/bcpkix-jdk15on-1.61.jar
       29  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcpkix-jdk15on/1.61/.jrubydir
       10  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcpkix-jdk15on/.jrubydir
   562610  2019-08-12 10:24   META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bctls-jdk15on/1.61/bctls-jdk15on-1.61.jar
```

**Comment by quesurifn** [comment]
I'm having this issue as well.

**Comment by headius** [comment]
Circling back since this woke up again...

@fun-ruby This line in your output looks worrisome:

> 283  2020-06-02 14:13   WEB-INF/gems/gems/jruby-openssl-0.10.2-java/lib/jopenssl.jar

I am not sure how this nearly-empty jar file got in there but if it is loaded instead of the larger one it could easily explain this issue.

@quesurifn Can you provide some log output and a description of how your app is built and deployed?

**Comment by quesurifn** [comment]
@headius It's `NameError: cannot load (ext) (org.jruby.ext.openssl.OpenSSL)`. This happens upon installation of jruby using RVM in Ubuntu Bionic on AWS EC2. It happens when installing the gemset though it seems the main installation works fine.

I saw a few GH issues that mentioned the same error for logstash and recommended using openjdk version 8 (1.8.0? their versioning system is confusing to me). I tried that and it didn't work. I also tried deleting the CA certs stored one of the jdk directories and purging all openjdk versions and reinstalling openjdk 1.8.0. 

So far nothing has worked.

**Comment by headius** [comment]
@quesurifn Can you provide more info about how you are running the code and what your environment looks like? You might also try passing `-d` to JRuby, possibly through JRUBY_OPTS env var.

There should be more output if it is the same issue as reported here, and it would indicate there's another version of jruby-openssl in your system somewhere.

**Comment by fun-ruby** [comment]
Just to clarify my original issue.

I was using `JRuby 9.2.8.0` with a more newer version of `jruby-openssl` (0.10.2 or 0.10.3 as can be seen in my logs). So my `Gemfile` included a newer version of `jruby-openssl`.

This configuration breaks with
```
config/warble.rb
  ...
  config.move_jars_to_webinf_lib = true
```
Commenting out the above line or set its value to `false` fixed this issue, for me.

HTH

**Comment by headius** [comment]
@fun-ruby Thank you for that update! Perhaps this qualifies as a warbler bug?

@quesurifn Are you packaging an app using warbler, and able to try this config change?
