### ISSUE TITLE
bundle install affected by DST Root CA X3 expiration 

### ISSUE THREAD

**Issue by LizhangX** [jruby/jruby-openssl#236]
Hi,

We are getting the below issue when doing bundle install with jruby today since the root CA is expired.
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
https://community.letsencrypt.org/t/help-thread-for-dst-root-ca-x3-expiration-september-2021/149190

```Retrying fetcher due to error (4/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://gems.contribsys.com/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Added /opt/jruby/lib/ruby/stdlib/rubygems/ssl_certs/rubygems.org/AddTrustExternalCARoot.pem to X509 store
Added /opt/jruby/lib/ruby/stdlib/rubygems/ssl_certs/rubygems.global.ssl.fastly.net/DigiCertHighAssuranceEVRootCA.pem to X509 store
Added /opt/jruby/lib/ruby/stdlib/rubygems/ssl_certs/index.rubygems.org/GlobalSignRootCA.pem to X509 store
SSL verification error at depth 2: unable to get local issuer certificate (20)
You must add /O=Digital Signature Trust Co./CN=DST Root CA X3 to your local trusted store
```

So basically it doesn't trust the first cert it finds in the chain even tho it is in the keystore.
DST Root CA X3 is not there, just like in the OS store.
If we add it to the key store, we are getting the below error.
```
SSL verification error at depth 3: certificate has expired (10)
Certificate /O=Digital Signature Trust Co./CN=DST Root CA X3 expired at 2021-09-30T14:01:15Z
```

Maybe this flag `X509_V_FLAG_TRUSTED_FIRST` should be added here https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/x509store/VerifyParameter.java#L153-L162

We tried bundle install with pure ruby and it is working fine. Then we noticed that jRuby is using this module instead of openssl.
Could we have some suggestions here please?

**Comment by Sharpie** [comment]
Could be the same root cause as #232 given both involve iterating through potential certificate chains in order to find the valid one.

**Comment by igcherkaev** [comment]
> Could be the same root cause as #232 given both involve iterating through potential certificate chains in order to find the valid one.

Hmm, I don't think so... In the case of expired DST Root CA X3 cert, it doesn't stop validation even though ISRG Root X1 cert is in the keystore and trusted. The `X509_V_FLAG_TRUSTED_FIRST` flag is probably not being set when it jopenssl asks OpenSSL to verify the chain of certs, so once it sees that ISRG Root X1 is issued by DST Root CA X3, it wants to validate it as well. 

curl, for example, made that change a while ago: https://github.com/curl/curl/commit/e2de2d53979ac6d93303562f5531f75944e70b8b

But what's bothering me is that OpenSSL 1.1.0 (which is the case with jruby docker images based on debian 9 stretch) says it enables that flag by default. So in theory this issue should not have popped up today at all, but it is what it is. Unless jopenssl overrides openssl's defaults somehow. 

Like, here, maybe: https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/x509store/VerifyParameter.java#L76

or, here: https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/x509store/VerifyParameter.java#L286

Because if you look here: https://github.com/openssl/openssl/blob/278260bfa238aefef5a1abe2043d2f812c3a4bd5/crypto/x509/x509_vpm.c#L513 - openssl sets that flag there, and it's probably not zero.

**Comment by bjoernhaeuser** [comment]
If Android 2-7 compatibility is not an issue for your certificates, you can also tell certbot to only use the new certificate chain:

```
--preferred-chain "ISRG Root X1"
```

(you maybe need to also set `--force-renewal` to get a net certificate. More information are [here](https://letsencrypt.org/2020/12/21/extending-android-compatibility.html).

**Comment by rhanka** [comment]
The problem appears also if you just use this lib to get when you don't manage certificates (cf above logstash issues), so it is blocking.

**Comment by jsvd** [comment]
Here is a reproducer for this issue: https://gist.github.com/jsvd/cdd0b7421bac7b2a00d64b644eba12c4

**Comment by jsvd** [comment]
Update: removing the expired root certificate from the JDK's truststore doesn't workaround the issue.
I used the following code to test it: https://gist.githubusercontent.com/jsvd/c72a51f5ffda234a0d12a590fb03ce82/raw/8fbddab6689880a49b8481c1121355713db85339/gistfile1.txt

The steps where:
1. ran the script and observed failed verify with error string: `certificate has expired`
2. deleted expired root cert from JDK's truststore: `bin/keytool -cacerts -delete -alias 'o=digital signature trust co.,cn=dst root ca x3'` (error code 10)
3. ran the script again and observed failed verify with different error string: `unable to get local issuer certificate` (error code: 20)

**Comment by igcherkaev** [comment]
> Update: removing the expired root certificate from the JDK's truststore doesn't workaround the issue. I used the following code to test it: https://gist.githubusercontent.com/jsvd/c72a51f5ffda234a0d12a590fb03ce82/raw/8fbddab6689880a49b8481c1121355713db85339/gistfile1.txt
> 
> The steps where:
> 
> 1. ran the script and observed failed verify with error string: `certificate has expired`
> 2. deleted expired root cert from JDK's truststore: `bin/keytool -cacerts -delete -alias 'o=digital signature trust co.,cn=dst root ca x3'` (error code 10)
> 3. ran the script again and observed failed verify with different error string: `unable to get local issuer certificate` (error code: 20)

Yeah, we tried the same, got same results. Hence, we created this issue as there seems to be no workaround available.

**Comment by tedhexaflow** [comment]
Not sure this is related but if it is something about DST Root CA X3 expiration for JRuby app with Nginx server, this may help https://github.com/jruby/jruby/issues/6872#issuecomment-934314911

**Comment by jordan-thoms** [comment]
Yeah, we're still being blocked by this - any progress on fixing this issue?

**Comment by jonathanswenson** [comment]
@kares I attempted to give the above release candidate a try  and was still unable to verify certain certificates that were broken recently: `https://helloworld.letsencrypt.org`

```
irb(main):003:0> JOpenSSL::VERSION
=> "0.11.0.cr1"
irb(main):004:0> puts Net::HTTP.get_response(URI('https://helloworld.letsencrypt.org'))
Traceback (most recent call last):
       11: from /nix/store/2q408llai3cm5xik323s9fyzfljhm0j5-jruby-9.2.16.0/bin/irb:13:in `<main>'
       10: from org/jruby/RubyKernel.java:1189:in `catch'
        9: from org/jruby/RubyKernel.java:1189:in `catch'
        8: from org/jruby/RubyKernel.java:1442:in `loop'
        7: from org/jruby/RubyKernel.java:1048:in `eval'
        6: from (irb):4:in `evaluate'
        5: from /nix/store/2q408llai3cm5xik323s9fyzfljhm0j5-jruby-9.2.16.0/lib/ruby/stdlib/net/http.rb:485:in `get_response'
        4: from /nix/store/2q408llai3cm5xik323s9fyzfljhm0j5-jruby-9.2.16.0/lib/ruby/stdlib/net/http.rb:609:in `start'
        3: from /nix/store/2q408llai3cm5xik323s9fyzfljhm0j5-jruby-9.2.16.0/lib/ruby/stdlib/net/http.rb:913:in `start'
        2: from /nix/store/2q408llai3cm5xik323s9fyzfljhm0j5-jruby-9.2.16.0/lib/ruby/stdlib/net/http.rb:924:in `do_start'
        1: from /nix/store/2q408llai3cm5xik323s9fyzfljhm0j5-jruby-9.2.16.0/lib/ruby/stdlib/net/http.rb:1002:in `connect'
OpenSSL::SSL::SSLError (certificate verify failed)
```

Is there something I’m missing here?

**Comment by kares** [comment]
Thanks Jonathan for looking - sorry this isn't merged on master yet (only in the PR). 
The build is challenging at times, same for CI and some of the (long-term) broken tests - planning to migrate to Gradle for a while but there's always smt else.

... and just to be clear for others reading, `https://helloworld.letsencrypt.org` works with 0.11.0 (fails with 0.10.7):
```ruby
require 'openssl'

puts JOpenSSL::VERSION if defined? JRUBY_VERSION

require 'net/http'

puts Net::HTTP.get_response(URI('https://helloworld.letsencrypt.org'))
```
```
jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 25.302-b08 on 1.8.0_302-b08 +jit [linux-x86_64]
0.11.0.cr1
#<Net::HTTPOK:0x4ce1d6d0>
```
