### ISSUE TITLE
OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by fjyaniez** [jruby/jruby-openssl#59]
Hi, I encountered a problem trying to retrieve a page using `Net::HTTP` through a SSL connection. Maybe I'm missing some configuration?

java

```
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

jruby

```
jruby 1.7.21 (1.9.3p551) 2015-07-07 a741a82 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_51-b16 +jit [linux-amd64]
```

Gemfile.lock

```
    jruby-openssl (0.9.8-java)
```

Steps:

``` ruby
uri = URI.parse('https://balupton.com')

http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.get('/')
```

Output:

``` ruby
OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure
    from org/jruby/ext/openssl/SSLSocket.java:190:in `connect'
    from /home/app/.rvm/rubies/jruby-1.7.21/lib/ruby/1.9/net/http.rb:800:in `connect'
    from org/jruby/ext/timeout/Timeout.java:106:in `timeout'
    from /home/app/.rvm/rubies/jruby-1.7.21/lib/ruby/1.9/net/http.rb:800:in `connect'
    from /home/app/.rvm/rubies/jruby-1.7.21/lib/ruby/1.9/net/http.rb:756:in `do_start'
    from /home/app/.rvm/rubies/jruby-1.7.21/lib/ruby/1.9/net/http.rb:745:in `start'
    from /home/app/.rvm/rubies/jruby-1.7.21/lib/ruby/1.9/net/http.rb:1293:in `request'
    from /home/app/.rvm/rubies/jruby-1.7.21/lib/ruby/1.9/net/http.rb:1035:in `get'
    from (irb):166:in `evaluate'
    from org/jruby/RubyKernel.java:1079:in `eval'
    from org/jruby/RubyKernel.java:1479:in `loop'
    from org/jruby/RubyKernel.java:1242:in `catch'
    from org/jruby/RubyKernel.java:1242:in `catch'
    from /home/app/shared/bundle/jruby/1.9/gems/railties-3.2.22/lib/rails/commands/console.rb:47:in `start'
    from /home/app/shared/bundle/jruby/1.9/gems/railties-3.2.22/lib/rails/commands/console.rb:8:in `start'
    from /home/app/shared/bundle/jruby/1.9/gems/railties-3.2.22/lib/rails/commands.rb:41:in `(root)'
    from org/jruby/RubyKernel.java:1040:in `require'
    from script/rails:6:in `(root)'jruby-1.7.21 :167 >
```
##

**Comment by nomadium** [comment]
This is weird, I don't think the bug is in jruby-openssl although I could be wrong, of course.

I tried to debug this and ran that code with another well SSL configured server like www.google.com and there were no handshake problems. I also tried with another web servers and jruby works OK.

However, when you try this with Cloudflare (where is hosted balupton.com) it dies because it receives unexpected data (according to JSSE implementation).

You can see it if you run jruby with ```"-Djavax.net.debug=all"```

```
[...]
trigger seeding of SecureRandom
done seeding SecureRandom
Using SSLEngineImpl.                                     
trigger seeding of SecureRandom
done seeding SecureRandom
Using SSLEngineImpl.
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
%% No cached client session
*** ClientHello, TLSv1
RandomCookie:  GMT: 1421724684 bytes = { 231, 188, 139, 148, 201, 199, 171, 225, 24, 134, 5, 41, 175, 8, 205, 134, 141, 15, 244, 255, 12, 93, 25, 144, 211, 214, 61, 157 }
Session ID:  {}
Cipher Suites: [TLS_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE
_DSS_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5, SSL_R
SA_WITH_DES_CBC_SHA, SSL_DHE_RSA_WITH_DES_CBC_SHA]
Compression Methods:  { 0 }
Extension server_name, server_name: [host_name: balupton.com]
Extension renegotiation_info, renegotiated_connection: <empty>
***
[write] MD5 and SHA1 hashes:  len = 97
0000: 01 00 00 5D 03 01 55 BE   CC 0C E7 BC 8B 94 C9 C7  ...]..U.........
0010: AB E1 18 86 05 29 AF 08   CD 86 8D 0F F4 FF 0C 5D  .....).........]
0020: 19 90 D3 D6 3D 9D 00 00   1A 00 35 00 39 00 38 00  ....=.....5.9.8.
0030: 2F 00 33 00 32 00 0A 00   16 00 13 00 05 00 04 00  /.3.2...........
0040: 09 00 15 01 00 00 1A 00   00 00 11 00 0F 00 00 0C  ................
0050: 62 61 6C 75 70 74 6F 6E   2E 63 6F 6D FF 01 00 01  balupton.com....
0060: 00                                                 .
main, WRITE: TLSv1 Handshake, length = 97
[Raw write]: length = 102
0000: 16 03 01 00 61 01 00 00   5D 03 01 55 BE CC 0C E7  ....a...]..U....
0010: BC 8B 94 C9 C7 AB E1 18   86 05 29 AF 08 CD 86 8D  ..........).....
0020: 0F F4 FF 0C 5D 19 90 D3   D6 3D 9D 00 00 1A 00 35  ....]....=.....5
0030: 00 39 00 38 00 2F 00 33   00 32 00 0A 00 16 00 13  .9.8./.3.2......
0040: 00 05 00 04 00 09 00 15   01 00 00 1A 00 00 00 11  ................
0050: 00 0F 00 00 0C 62 61 6C   75 70 74 6F 6E 2E 63 6F  .....balupton.co
0060: 6D FF 01 00 01 00                                  m.....
[Raw read]: length = 5
0000: 15 03 01 00 02                                     .....
[Raw read]: length = 2
0000: 02 28                                              .(
main, READ: TLSv1 Alert, length = 2
main, RECV TLSv1 ALERT:  fatal, handshake_failure
[...]
```

The full stack trace including JSSE classes:

```
javax.net.ssl.SSLException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1650)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1618)
        at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1787)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1071)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:893)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:767)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.jruby.ext.openssl.SSLSocket.readAndUnwrap(SSLSocket.java:554)
        at org.jruby.ext.openssl.SSLSocket.doHandshake(SSLSocket.java:433)
        at org.jruby.ext.openssl.SSLSocket.connectCommon(SSLSocket.java:213)
        at org.jruby.ext.openssl.SSLSocket.connect(SSLSocket.java:190)
```

Maybe the bug is in SSE or CloudFlare is doing something non standardised in their SSL endpoints?

**Comment by kares** [comment]
yes, you're on the right track ... maybe try disabling DHE (see #45). also our cipher list might not be fully mapped and matching does not match what C OpenSSL is doing https://github.com/jruby/jruby-openssl/issues/50#issuecomment-114456686 (need help on those fronts)

**Comment by nomadium** [comment]
Ok, thanks for the info. I'll try again and let you know if I find something useful.

**Comment by jordan-thoms** [comment]
Also seeing this behavior when connecting to wufoo.com . Did you ever find a solution? I've tried using OpenJDK 8 and this issue is still present. I see very similar debug logs:
```
trustStore is: No File Available, using empty keystore.
trustStore type is : jks
trustStore provider is :
init truststore
trigger seeding of SecureRandom
done seeding SecureRandom
Using SSLEngineImpl.
trigger seeding of SecureRandom
done seeding SecureRandom
Using SSLEngineImpl.
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
%% No cached client session
*** ClientHello, TLSv1.2
RandomCookie:  GMT: 1440650141 bytes = { 171, 60, 40, 230, 73, 189, 221, 36, 105, 128, 130, 37, 60, 42, 7, 135, 237, 178, 131, 245, 98, 144, 26, 26, 250, 97, 23, 22 }
Session ID:  {}
Cipher Suites: [TLS_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_DES_CBC_SHA, SSL_DHE_RSA_WITH_DES_CBC_SHA]
Compression Methods:  { 0 }
Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA224withECDSA, SHA224withRSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA, MD5withRSA
Extension server_name, server_name: [type=host_name (0), value=wufoo.com]
Extension renegotiation_info, renegotiated_connection: <empty>
***
[write] MD5 and SHA1 hashes:  len = 120
0000: 01 00 00 74 03 03 56 DF   94 9D AB 3C 28 E6 49 BD  ...t..V....<(.I.
0010: DD 24 69 80 82 25 3C 2A   07 87 ED B2 83 F5 62 90  .$i..%<*......b.
0020: 1A 1A FA 61 17 16 00 00   16 00 35 00 39 00 38 00  ...a......5.9.8.
0030: 2F 00 33 00 32 00 0A 00   16 00 13 00 09 00 15 01  /.3.2...........
0040: 00 00 35 00 0D 00 1A 00   18 06 03 06 01 05 03 05  ..5.............
0050: 01 04 03 04 01 03 03 03   01 02 03 02 01 02 02 01  ................
0060: 01 00 00 00 0E 00 0C 00   00 09 77 75 66 6F 6F 2E  ..........wufoo.
0070: 63 6F 6D FF 01 00 01 00                            com.....
main, WRITE: TLSv1.2 Handshake, length = 120
[Raw write]: length = 125
0000: 16 03 03 00 78 01 00 00   74 03 03 56 DF 94 9D AB  ....x...t..V....
0010: 3C 28 E6 49 BD DD 24 69   80 82 25 3C 2A 07 87 ED  <(.I..$i..%<*...
0020: B2 83 F5 62 90 1A 1A FA   61 17 16 00 00 16 00 35  ...b....a......5
0030: 00 39 00 38 00 2F 00 33   00 32 00 0A 00 16 00 13  .9.8./.3.2......
0040: 00 09 00 15 01 00 00 35   00 0D 00 1A 00 18 06 03  .......5........
0050: 06 01 05 03 05 01 04 03   04 01 03 03 03 01 02 03  ................
0060: 02 01 02 02 01 01 00 00   00 0E 00 0C 00 00 09 77  ...............w
0070: 75 66 6F 6F 2E 63 6F 6D   FF 01 00 01 00           ufoo.com.....
[Raw read]: length = 5
0000: 15 03 03 00 02                                     .....
[Raw read]: length = 2
0000: 02 28                                              .(
main, READ: TLSv1.2 Alert, length = 2
main, RECV TLSv1.2 ALERT:  fatal, handshake_failure
main, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure
main, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure
main, called closeOutbound()
main, closeOutboundInternal()
main, SEND TLSv1.2 ALERT:  warning, description = close_notify
main, WRITE: TLSv1.2 Alert, length = 2
[Raw write]: length = 7
0000: 15 03 03 00 02 01 00                               .......
main, called closeOutbound()
main, closeOutboundInternal()
OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure
	from org/jruby/ext/openssl/SSLSocket.java:215:in `connect'
	from /opt/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:927:in `block in connect'
	from org/jruby/ext/timeout/Timeout.java:127:in `timeout'
	from /opt/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:927:in `connect'
	from /opt/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:867:in `do_start'
	from /opt/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:856:in `start'
	from /opt/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:1388:in `request'
	from /opt/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:1146:in `get'
	from (irb):33:in `<eval>'
	from org/jruby/RubyKernel.java:976:in `eval'
	from org/jruby/RubyKernel.java:1287:in `loop'
	from org/jruby/RubyKernel.java:1096:in `catch'
	from org/jruby/RubyKernel.java:1096:in `catch'
	from /opt/jruby-9.0.5.0/bin/irb:13:in `<top>'

```

It seems that '(' it's getting from the server is upsetting it. This seems to work when using pure Java code though. Testing with openssl s_client, it fails with version 0.9.8zg , but works with 1.0.1f. So all very strange.

Did you ever find a solution?

**Comment by albertogg** [comment]
Hello, I'm seeing the exact same issue. Not sure what's wrong I've tried a bunch of things including #45 and things mentioned in #50 but still getting the same issue. This is happening with `jruby-1.7.24` and `jruby-9.0.5.0`, running in either `oracle64-1.7.0.79` or `oracle64-1.8.0.77`.

I'm using this snippet to reproduce the error:

```ruby
require "net/https"

if RUBY_PLATFORM == "java"
  java.security.Security.setProperty("jdk.tls.disabledAlgorithms", "SSLv3, DHE")
end

uri = URI.parse("https://balupton.com")
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
http.ssl_version = :TLSv1_2

request = Net::HTTP::Get.new(uri.request_uri)
response = http.request(request)

puts response
```

Running the snippet with debug enabled `jruby -J-Djavax.net.debug=all -S jruby-openssl-test.rb` gives me this:

```
trigger seeding of SecureRandom
done seeding SecureRandom
Using SSLEngineImpl.
trigger seeding of SecureRandom
done seeding SecureRandom
Using SSLEngineImpl.
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring obsoleted cipher suite: SSL_RSA_WITH_DES_CBC_SHA
%% No cached client session
*** ClientHello, TLSv1.2
RandomCookie:  GMT: 1461102474 bytes = { 172, 17, 125, 195, 116, 187, 71, 247, 224, 69, 114, 129, 120, 220, 220, 224, 63, 141, 188, 242, 118, 154, 232, 106, 29, 222, 175, 159 }
Session ID:  {}
Cipher Suites: [TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5]
Compression Methods:  { 0 }
Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA224withECDSA, SHA224withRSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
Extension server_name, server_name: [type=host_name (0), value=balupton.com]
Extension renegotiation_info, renegotiated_connection: <empty>
***
[write] MD5 and SHA1 hashes:  len = 109
0000: 01 00 00 69 03 03 57 17   A8 8A AC 11 7D C3 74 BB  ...i..W.......t.
0010: 47 F7 E0 45 72 81 78 DC   DC E0 3F 8D BC F2 76 9A  G..Er.x...?...v.
0020: E8 6A 1D DE AF 9F 00 00   0A 00 35 00 2F 00 0A 00  .j........5./...
0030: 05 00 04 01 00 00 36 00   0D 00 18 00 16 06 03 06  ......6.........
0040: 01 05 03 05 01 04 03 04   01 03 03 03 01 02 03 02  ................
0050: 01 02 02 00 00 00 11 00   0F 00 00 0C 62 61 6C 75  ............balu
0060: 70 74 6F 6E 2E 63 6F 6D   FF 01 00 01 00           pton.com.....
main, WRITE: TLSv1.2 Handshake, length = 109
[Raw write]: length = 114
0000: 16 03 03 00 6D 01 00 00   69 03 03 57 17 A8 8A AC  ....m...i..W....
0010: 11 7D C3 74 BB 47 F7 E0   45 72 81 78 DC DC E0 3F  ...t.G..Er.x...?
0020: 8D BC F2 76 9A E8 6A 1D   DE AF 9F 00 00 0A 00 35  ...v..j........5
0030: 00 2F 00 0A 00 05 00 04   01 00 00 36 00 0D 00 18  ./.........6....
0040: 00 16 06 03 06 01 05 03   05 01 04 03 04 01 03 03  ................
0050: 03 01 02 03 02 01 02 02   00 00 00 11 00 0F 00 00  ................
0060: 0C 62 61 6C 75 70 74 6F   6E 2E 63 6F 6D FF 01 00  .balupton.com...
0070: 01 00                                              ..
[Raw read]: length = 5
0000: 15 03 03 00 02                                     .....
[Raw read]: length = 2
0000: 02 28                                              .(
main, READ: TLSv1.2 Alert, length = 2
main, RECV TLSv1.2 ALERT:  fatal, handshake_failure
main, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure
main, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure
main, called closeOutbound()
main, closeOutboundInternal()
main, SEND TLSv1.2 ALERT:  warning, description = close_notify
main, WRITE: TLSv1.2 Alert, length = 2
[Raw write]: length = 7
0000: 15 03 03 00 02 01 00                               .......
main, called closeOutbound()
main, closeOutboundInternal()
OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure
           connect at org/jruby/ext/openssl/SSLSocket.java:215
  block in connect at /Users/albertogg/.rbenv/versions/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:927
           timeout at org/jruby/ext/timeout/Timeout.java:127
           connect at /Users/albertogg/.rbenv/versions/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:927
          do_start at /Users/albertogg/.rbenv/versions/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:867
             start at /Users/albertogg/.rbenv/versions/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:856
           request at /Users/albertogg/.rbenv/versions/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:1388
             <top> at jruby-openssl-test.rb:14
```

Thanks,

**Comment by albertogg** [comment]
Hi, for anyone having this problem I've solved it by updating the Java Cryptography Extension (JCE). It might or might not work for everyone but It solved my problem.

**Comment by amo13** [comment]
After experiencing this same issue, I dug a bit more into it because I was not able to resolve it by updating JCE.
I found out that the problem was with the ciphers. There were no common ciphers between my nginx+letsencrypt server and jruby+openssl. My solution for now was to allow a cipher considered deprecated on my server and now my jruby client connects successfully. 
Is there a chance that openssl for jruby is going to update the deprecated cipher suites? I am now seeing handshake problems with more sites that just my own server, but in that case, I can't add older ciphers to the servers.
